name: E2E Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/web/e2e/**'
      - 'apps/web/src/**'
      - 'apps/web/package.json'
      - 'apps/web/playwright.config.ts'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/web/e2e/**'
      - 'apps/web/src/**'
      - 'apps/web/package.json'
      - 'apps/web/playwright.config.ts'
  workflow_dispatch: # Allow manual trigger

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test on multiple browsers
        browser: [chromium, firefox, webkit]
        # Test on multiple viewport sizes
        viewport: [desktop, mobile]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Start application
        run: |
          cd apps/web
          npm run start &
          sleep 15
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Run E2E tests
        run: |
          cd apps/web
          if [ "${{ matrix.browser }}" = "chromium" ] && [ "${{ matrix.viewport }}" = "desktop" ]; then
            npm run test:e2e -- branch-management-simple.spec.ts --project=chromium --reporter=github
          elif [ "${{ matrix.browser }}" = "chromium" ] && [ "${{ matrix.viewport }}" = "mobile" ]; then
            npm run test:e2e -- branch-management-simple.spec.ts --project=chromium --reporter=github --config=playwright-mobile.config.ts
          else
            npm run test:e2e -- branch-management-simple.spec.ts --project=${{ matrix.browser }} --reporter=github
          fi
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}-${{ matrix.viewport }}
          path: apps/web/playwright-report/
          retention-days: 30

      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-videos-${{ matrix.browser }}-${{ matrix.viewport }}
          path: apps/web/test-results/
          retention-days: 7

  # Job for running all E2E tests together
  e2e-tests-all:
    runs-on: ubuntu-latest
    needs: e2e-tests
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

      - name: Start application
        run: |
          cd apps/web
          npm run start &
          sleep 15
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Run all E2E tests
        run: npm run test:e2e -- --reporter=github
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Upload comprehensive test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: comprehensive-playwright-report
          path: apps/web/playwright-report/
          retention-days: 30
